# Generated by Django 4.2.7 on 2023-11-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('shipping_address', models.CharField(max_length=100, verbose_name='Shipping Address')),
                ('shipping_city', models.CharField(max_length=30, verbose_name='City')),
                ('shipping_state', models.CharField(max_length=15, verbose_name='State')),
                ('shipping_zipcode', models.IntegerField()),
            ],
        ),
    ]
