# Generated by Django 4.2.7 on 2023-11-08 03:01
from django.db import migrations

# FOR TESTING
def create_data(apps, schema_editor):
    User = apps.get_model('database', 'User')
    User(first_name="Joe", last_name="Test", email="joe@email.com", birthdate="1900-01-01",
         shipping_address="100 Fake Ave", shipping_city="New York", shipping_state="New York",
         shipping_zipcode="10000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        # add for testing:
        migrations.RunPython(create_data),
    ]
