# Generated by Django 4.2.7 on 2023-12-01 06:59

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='The unique identifer for this restaurant.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('favoriters', models.ManyToManyField(related_name='favorite_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
