# Generated by Django 4.2.7 on 2023-12-02 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='favoriters',
            field=models.ManyToManyField(blank=True, related_name='favorite_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
