# Generated by Django 4.2.7 on 2023-12-02 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_restaurant_favoriters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='favoriters',
            field=models.ManyToManyField(blank=True, related_name='favorite_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_in_cents', models.IntegerField()),
                ('img_url', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('favoriters', models.ManyToManyField(blank=True, related_name='favorite_menu_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='items_on_menu', to='api.menuitem'),
        ),
    ]
