# Generated by Django 4.2.7 on 2023-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurant_favoriters_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_items',
            field=models.ManyToManyField(blank=True, related_name='restaurant_with_menu', to='api.menuitem'),
        ),
    ]
