# Generated by Django 4.2.7 on 2023-12-07 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_menu_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='openNow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_for_item', to='api.menu'),
        ),
    ]
